name: AI Quality Check

on:
  workflow_dispatch:
    inputs:
      client_folder:
        description: 'The folder name of the client'
        required: true
      task_path:
        description: 'Path of the task to check'
        required: true
      form_data_json:
        description: 'JSON string of the data entered by the agent'
        required: true

jobs:
  run-ai-qc:
    runs-on: ubuntu-latest

    steps:
      - name: Call AwanLLM for QC
        id: ai_check
        run: |
          # ... (Yeh poora step bilkul waisa hi rahega jaisa pehle tha) ...
          API_RESPONSE_FILE=$(mktemp)
          curl -s -X POST "https://api.awanllm.com/v1/chat/completions" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.AWANLLM_API_KEY }}" \
            -d '{
              "model": "Awan-Llama-13B-Chat-v1",
              "messages": [
                { "role": "system", "content": "You are a strict QC bot. Check if all JSON values are non-empty. Respond with only one word in lowercase: passed or failed." },
                { "role": "user", "content": "Data to check: ${{ github.event.inputs.form_data_json }}. Does this data pass?" }
              ]
            }' > "$API_RESPONSE_FILE"
          AI_RESULT=$(cat "$API_RESPONSE_FILE" | jq -r '.choices[0].message.content' | tr '[:upper:]' '[:lower:]' | xargs )
          echo "AI Result: $AI_RESULT"
          echo "qc_status=$AI_RESULT" >> $GITHUB_OUTPUT

      - name: Trigger Main Workflow based on AI result
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DB_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: post-ai-qc-action
          client-payload: >
            {
              "client_folder": "${{ github.event.inputs.client_folder }}",
              "task_path": "${{ github.event.inputs.task_path }}",
              "qc_status": "${{ steps.ai_check.outputs.qc_status }}"
            }
