name: BPO Job Processor

on:
  workflow_dispatch:
    inputs:
      client_folder:
        required: true
      job_name:
        required: true
      zip_file_base64:
        required: true
      schema_json:
        required: false
      triggered_by:
        required: false
        default: 'system'

jobs:
  process-zip-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DB Repo
        uses: actions/checkout@v4
        with:
          repository: larrydispatcherfdsales-blip/workflow-engine-db
          path: db
          token: ${{ secrets.DB_ACCESS_TOKEN }}
          ref: main

      - name: Decode and Save ZIP file
        run: |
          mkdir -p temp_zip
          echo "${{ github.event.inputs.zip_file_base64 }}" | base64 --decode > temp_zip/tasks.zip

      - name: Unzip tasks into client todo folder
        working-directory: ./db
        run: |
          CLIENT_FOLDER=${{ github.event.inputs.client_folder }}
          mkdir -p "$CLIENT_FOLDER/tasks/todo"
          unzip -o ../temp_zip/tasks.zip -d "$CLIENT_FOLDER/tasks/todo"

      - name: Save Job Schema
        # Yeh step ab hamesha chalega, taake khaali schema bhi save ho sake
        if: github.event.inputs.schema_json
        working-directory: ./db
        run: |
          CLIENT_FOLDER=${{ github.event.inputs.client_folder }}
          mkdir -p "$CLIENT_FOLDER/jobs"
          echo '${{ github.event.inputs.schema_json }}' > "$CLIENT_FOLDER/jobs/${{ github.event.inputs.job_name }}_schema.json"

      - name: Commit and Push New Tasks and Schema
        working-directory: ./db
        run: |
          TRIGGERED_BY=${{ github.event.inputs.triggered_by }}
          CLIENT_FOLDER=${{ github.event.inputs.client_folder }}
          
          git config user.name "$TRIGGERED_BY"
          git config user.email "$TRIGGERED_BY@users.noreply.github.com"
          
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Job Upload: By $TRIGGERED_BY for job '${{ github.event.inputs.job_name }}' in client '$CLIENT_FOLDER'"
            git push origin main
          else
            echo "No new content found to commit."
          fi
