name: BPO Job Processor

on:
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Name of the job being processed'
        required: true
      zip_file_base64:
        description: 'Base64 encoded content of the uploaded ZIP file'
        required: true
      schema_json:
        description: 'JSON string of the custom fields schema'
        required: false

jobs:
  process-zip-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DB Repo
        uses: actions/checkout@v4
        with:
          repository: larrydispatcherfdsales-blip/workflow-engine-db
          path: db
          token: ${{ secrets.DB_ACCESS_TOKEN }}
          ref: main

      - name: Decode and Save ZIP file
        run: |
          mkdir -p temp_zip
          echo "${{ github.event.inputs.zip_file_base64 }}" | base64 --decode > temp_zip/tasks.zip

      - name: Unzip tasks into todo folder
        working-directory: ./db/tasks/todo
        run: |
          unzip -o ../../../temp_zip/tasks.zip

      # --- YEH NAYA STEP HAI ---
      - name: Save Job Schema
        # Yeh step sirf tab chalega agar schema_json khaali nahi hai
        if: ${{ github.event.inputs.schema_json != '[]' && github.event.inputs.schema_json != '' }}
        working-directory: ./db
        run: |
          # 'jobs' ka folder banayein agar mojood nahi hai
          mkdir -p jobs
          # Schema ko uske job name ke sath save karein
          echo '${{ github.event.inputs.schema_json }}' > "jobs/${{ github.event.inputs.job_name }}_schema.json"

      - name: Commit and Push New Tasks and Schema
        working-directory: ./db
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@github.com"
          
          # Tamam nayi files (tasks aur schema) ko add karna
          git add .
          
          if ! git diff --staged --quiet; then
            echo "New tasks/schema found. Committing and pushing..."
            git commit -m "Job Upload: Added new tasks and schema for job '${{ github.event.inputs.job_name }}'"
            git push origin main
          else
            echo "No new files to commit."
          fi
