name: BPO WorkFlow Engine

on:
  workflow_dispatch:
    inputs:
      client_folder:
        required: true
      action:
        required: true
      task_path:
        required: false
      form_data_json:
        required: false
      triggered_by:
        required: false
        default: 'system'
  repository_dispatch:
    types: [post-ai-qc-action]

jobs:
  manage_tasks:
    runs-on: ubuntu-latest
    outputs:
      fetched_task_path: ${{ steps.perform_action.outputs.new_task_path }}

    steps:
      - name: Checkout DB Repo
        uses: actions/checkout@v4
        with:
          repository: larrydispatcherfdsales-blip/workflow-engine-db
          path: db
          token: ${{ secrets.DB_ACCESS_TOKEN }}
          ref: main

      - name: Perform Action and Push Changes
        id: perform_action
        working-directory: ./db
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            TRIGGERED_BY=${{ github.event.client_payload.triggered_by }}
            CLIENT_FOLDER=${{ github.event.client_payload.client_folder }}
            TASK_PATH=${{ github.event.client_payload.task_path }}
            QC_STATUS=${{ github.event.client_payload.qc_status }}
            ACTION="ai_qc_result"
          else
            TRIGGERED_BY=${{ github.event.inputs.triggered_by }}
            CLIENT_FOLDER=${{ github.event.inputs.client_folder }}
            ACTION=${{ github.event.inputs.action }}
            TASK_PATH=${{ github.event.inputs.task_path }}
            FORM_DATA=${{ github.event.inputs.form_data_json }}
          fi
          
          git config user.name "$TRIGGERED_BY"
          git config user.email "$TRIGGERED_BY@users.noreply.github.com"

          echo "Processing for client: $CLIENT_FOLDER | Action: $ACTION | Triggered by: $TRIGGERED_BY"

          # ... (Baqi tamam logic - if/elif/else - bilkul waisa hi rahega) ...

          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Client: $CLIENT_FOLDER | User: $TRIGGERED_BY | Action: $ACTION"
            git push origin main
          else
            echo "No changes to commit."
          fi
