name: BPO WorkFlow Engine

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (fetch, submit, approve, reject)'
        required: true
        type: choice
        options:
          - fetch_task
          - submit_for_qc
          - approve_qc
          - reject_qc
      task_path:
        description: 'Path of the task to act on (e.g., tasks/inprogress/task1.txt)'
        required: false

jobs:
  manage_tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Backend Repo
        uses: actions/checkout@v4
        with:
          path: backend

      - name: Checkout DB Repo
        uses: actions/checkout@v4
        with:
          repository: larrydispatcherfdsales-blip/workflow-engine-db
          path: db
          token: ${{ secrets.DB_ACCESS_TOKEN }}
          ref: main

      - name: Perform Action and Push Changes
        id: perform_action
        working-directory: ./db
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@github.com"

          ACTION=${{ github.event.inputs.action }}
          TASK_PATH=${{ github.event.inputs.task_path }}

          echo "Performing action: $ACTION"

          if [ "$ACTION" == "fetch_task" ]; then
            TASK_TO_FETCH=$(find tasks/todo -type f -name "*.txt" | head -n 1)
            if [ -z "$TASK_TO_FETCH" ]; then
              echo "No tasks to fetch."
              exit 0
            fi
            mkdir -p tasks/inprogress
            NEW_PATH="tasks/inprogress/$(basename $TASK_TO_FETCH)"
            git mv "$TASK_TO_FETCH" "$NEW_PATH"
            echo "Fetched task: $TASK_TO_FETCH and moved to $NEW_PATH"
            echo "new_task_path=$NEW_PATH" >> $GITHUB_OUTPUT
          fi
          
          # (Yahan baqi actions ka logic aayega)

          # --- YAHAN ASAL TABDEELI HAI ---
          # Tamam tabdeeliyon ko "stage" karna
          git add .

          # Check karein ke koi staged changes hain ya nahi
          if ! git diff --staged --quiet; then
            echo "Changes detected. Committing and pushing..."
            git commit -m "Workflow: Performed '$ACTION'"
            git push origin main
          else
            echo "No changes to commit."
          fi
