name: BPO WorkFlow Engine

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (fetch, submit, approve, reject)'
        required: true
        type: choice
        options:
          - fetch_task
          - submit_for_qc
          - approve_qc
          - reject_qc
      task_path:
        description: 'Path of the task to act on (e.g., tasks/inprogress/task1.txt)'
        required: false

jobs:
  manage_tasks:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Backend repo ko checkout karna (Optional, lekin achi practice hai)
      - name: Checkout Backend Repo
        uses: actions/checkout@v4
        with:
          path: backend

      # Step 2: DB repo ko checkout karna (Sab se ahem step)
      - name: Checkout DB Repo
        uses: actions/checkout@v4
        with:
          # Yaqeen karein ke yeh aapke DB repo ka sahi address hai
          repository: larrydispatcherfdsales-blip/workflow-engine-db
          path: db
          # Yeh aapke banaye hue secret se asli token (ghp_...) haasil karega
          token: ${{ secrets.DB_ACCESS_TOKEN }}

      # Step 3: Action ke mutabiq kaam karna
      - name: Perform Action on Task
        id: perform_action
        working-directory: ./db
        run: |
          ACTION=${{ github.event.inputs.action }}
          TASK_PATH=${{ github.event.inputs.task_path }}

          echo "Performing action: $ACTION"

          if [ "$ACTION" == "fetch_task" ]; then
            TASK_TO_FETCH=$(find tasks/todo -type f | head -n 1)
            if [ -z "$TASK_TO_FETCH" ]; then
              echo "No tasks to fetch in 'todo' folder."
              exit 0
            fi
            mkdir -p tasks/inprogress
            NEW_PATH="tasks/inprogress/$(basename $TASK_TO_FETCH)"
            git mv "$TASK_TO_FETCH" "$NEW_PATH"
            echo "Fetched task: $TASK_TO_FETCH and moved to $NEW_PATH"
            echo "new_task_path=$NEW_PATH" >> $GITHUB_OUTPUT

          elif [ "$ACTION" == "submit_for_qc" ]; then
            if [ -z "$TASK_PATH" ]; then echo "Error: task_path is required for this action."; exit 1; fi
            mkdir -p tasks/in_qc
            NEW_PATH="tasks/in_qc/$(basename $TASK_PATH)"
            git mv "$TASK_PATH" "$NEW_PATH"
            echo "Submitted for QC: $TASK_PATH -> $NEW_PATH"

          elif [ "$ACTION" == "approve_qc" ]; then
            if [ -z "$TASK_PATH" ]; then echo "Error: task_path is required for this action."; exit 1; fi
            mkdir -p tasks/completed
            NEW_PATH="tasks/completed/$(basename $TASK_PATH)"
            git mv "$TASK_PATH" "$NEW_PATH"
            echo "Approved QC: $TASK_PATH -> $NEW_PATH"

          elif [ "$ACTION" == "reject_qc" ]; then
            if [ -z "$TASK_PATH" ]; then echo "Error: task_path is required for this action."; exit 1; fi
            mkdir -p tasks/todo
            NEW_PATH="tasks/todo/$(basename $TASK_PATH)"
            git mv "$TASK_PATH" "$NEW_PATH"
            echo "Rejected QC: $TASK_PATH -> $NEW_PATH"
          fi

          # Step 4: Changes ko DB repo mein wapas push karna
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@github.com"
          # Check karein ke koi tabdeeli hui hai ya nahi, phir hi commit/push karein
          if ! git diff --quiet --exit-code; then
            git commit -m "Workflow: Performed '$ACTION'"
            git push
          else
            echo "No changes to commit."
          fi
