name: BPO WorkFlow Engine

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (fetch, submit, approve, reject)'
        required: true
        type: choice
        options:
          - fetch_task
          - submit_for_qc
          - approve_qc
          - reject_qc
      task_path:
        description: 'Path of the task to act on (e.g., tasks/inprogress/task1.txt)'
        required: false

jobs:
  manage_tasks:
    runs-on: ubuntu-latest
    # --- YEH NAYA HISSA ADD KAREIN ---
    # Job ke outputs ko define karna
    outputs:
      fetched_task_path: ${{ steps.perform_action.outputs.new_task_path }}

    steps:
      - name: Checkout Backend Repo
        uses: actions/checkout@v4
        with:
          path: backend

      - name: Checkout DB Repo
        uses: actions/checkout@v4
        with:
          repository: chuh31481-wq/workflow-engine-db
          path: db
          token: ${{ secrets.DB_ACCESS_TOKEN }}

      # --- IS STEP KO EK ID DENI HAI ---
      - name: Perform Action on Task
        id: perform_action # Is step ko ek ID de di
        working-directory: ./db
        run: |
          ACTION=${{ github.event.inputs.action }}
          TASK_PATH=${{ github.event.inputs.task_path }}

          echo "Performing action: $ACTION"

          if [ "$ACTION" == "fetch_task" ]; then
            TASK_TO_FETCH=$(find tasks/todo -type f | head -n 1)
            if [ -z "$TASK_TO_FETCH" ]; then
              echo "No tasks to fetch."
              exit 0
            fi
            mkdir -p tasks/inprogress
            NEW_PATH="tasks/inprogress/$(basename $TASK_TO_FETCH)"
            git mv "$TASK_TO_FETCH" "$NEW_PATH"
            echo "Fetched task: $TASK_TO_FETCH and moved to $NEW_PATH"
            # --- YAHAN ASAL TABDEELI HAI ---
            # Fetched task ka path output variable mein set karna
            echo "new_task_path=$NEW_PATH" >> $GITHUB_OUTPUT

          # ... (baqi if conditions waisi hi rahengi) ...
          elif [ "$ACTION" == "submit_for_qc" ]; then
            # ...
          fi

          # Changes ko push karna
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@github.com"
          if ! git diff --quiet; then
            git commit -m "Workflow: Performed '$ACTION'"
            git push
          else
            echo "No changes to commit."
          fi

